-- MySql toturial
-- some of the most important SQL commands
-- SELECT
-- DELETE
-- INSERT INTO
-- CREATE DATABASE
-- CREATE TABEL
-- ALTER TABLE
-- CREATE INDEX
-- DROP INDEX

-- MY-SQL SELECT STATEMENT
SELECT COLUMN1, COLUMN2
FROM TABLE_NAME

-- TO SELECT ALL ELEMENTS IN A TABLE
SELECT *
FROM TABLE_NAME

-- IF WE HAVE A DEMO TALBE NAMED Customers wiht some table colums

SELECT CustomerNamw, City, Country
FROM Customers

SELECT *
FROM Customers

-- TO SELECT DISTINCT VALUES FROM A COLUMN
SELECT DISTINCT Country
FROM Customers

-- TO SELECT THE COUNT OF IDSTINCT VALUES FROM A COLUMN

SELECT COUNT(DISTINCT Country) AS NumberOfCountries
FROM Customers

-- TO SELECT ROWS WHERE A CONDITION IS TRUE
SELECT *
FROM Customers

WHERE Country = 'USA'

-- TO SELECT ROWS WHERE A CONDITION IS TRUE AND ANOTHER CONDITION IS TRUE
SELECT *
FROM Customers

WHERE Country = 'USA' AND City = 'New York'

-- TO SELECT ROWS WHERE A CONDITION IS TRUE OR ANOTHER CONDITION IS TRUE
SELECT *

FROM Customers

WHERE Country = 'USA' OR Country = 'Canada'

-- TO SELECT ROWS WHERE A CONDITION IS NOT TRUE 

-- (Note: NOT operator is used to reverse the condition)

SELECT *

FROM Customers

WHERE Country != 'USA'

-- TO SELECT ROWS WHERE A COLUMN HAS A VALUE BETWEEN A MINIMUM AND MAXIMUM

SELECT *

FROM Customers

WHERE Age BETWEEN 25 AND 30

-- TO SELECT ROWS WHERE A COLUMN HAS A VALUE GREATER THAN A MINIMUM

SELECT *

FROM Customers

WHERE Age > 25

-- TO SELECT ROWS WHERE A COLUMN HAS A VALUE LESS THAN A MAXIMUM

SELECT *

FROM Customers

WHERE Age < 30

-- TO SELECT ROWS WHERE A COLUMN HAS A VALUE GREATER THAN OR EQUAL TO A MINIMUM

SELECT *

FROM Customers

WHERE Age >= 25

-- TO SELECT ROWS WHERE A COLUMN HAS A VALUE LESS THAN OR EQUAL TO A MAXIMUM

SELECT *

FROM Customers

WHERE Age <= 30

-- TO SELECT ROWS WHERE A COLUMN CONTAINS A SPECIFIED STRING

SELECT *
